version: '3.1'

volumes:
   geo-db-data:
   pgadmin-data:

services:

   geoserver:
      image: kartoza/geoserver:${GS_VERSION}
      volumes:
        - ./geoserver/data:/opt/geoserver/data_dir
        - ./geoserver/epsg.properties:/settings/epsg.properties
      ports:
        - ${GEOSERVER_PORT}:8080
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3



   mapstore:
           #      build: ./st-geovisor
      image: geosolutionsit/mapstore2
      ports:
        - ${MAPSTORE_PORT}:8080  

   

   geoapi:
      build: ./st-geoapi
      image: st-geoapi
      ports:
        - ${GEOAPI_PORT}:5000  
      environment:
        - GEOSERVER_URL=${GEOSERVER_URL}
        - GEOSERVER_GC_URL=${GEOSERVER_GC_URL}
        - GEOSERVER_USER=${GEOSERVER_USER}
        - GEOSERVER_PASSWD=${GEOSERVER_PASSWD}
        - GEOSERVER_PUBLIC_URL=${GEOSERVER_PUBLIC_URL}
        - GEOSERVER_GC_PUBLIC_URL=${GEOSERVER_GC_PUBLIC_URL}
        - MAPSTORE_URL=${MAPSTORE_URL}
        - MAPSTORE_USER=${MAPSTORE_USER}
        - MAPSTORE_PASSWD=${MAPSTORE_PASSWD}
        - MAPSTORE_PUBLIC_URL=${MAPSTORE_PUBLIC_URL}
