version: '3.9'

volumes:
   geo-db-data:
   pgadmin-data:

services:
   db:
      image: kartoza/postgis:${POSTGIS_VERSION_TAG}
      volumes:
         - geo-db-data:/var/lib/postgresql
      ports:
        - ${POSTGRES_PORT}:5432
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
        - FORCE_SSL=TRUE
        - RECREATE_DATADIR=FALSE
      restart: on-failure
      healthcheck:
        test: "exit 0"

   geoserver:
      image: kartoza/geoserver:${GS_VERSION}
      volumes:
        - ./geoserver/data:/opt/geoserver/data_dir
        - ./geoserver/epsg.properties:/settings/epsg.properties
      ports:
        - ${GEOSERVER_PORT}:8080
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      depends_on:
        db:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3

   pgadmin:
      image: dpage/pgadmin4
      volumes:
         - pgadmin-data:/var/lib/pgadmin
      ports:
        - 5050:80  
      environment:
        - PGADMIN_DEFAULT_EMAIL=aranguren@denebinc.com
        - PGADMIN_DEFAULT_PASSWORD=SuperSecret



   mapstore:
           #      build: ./st-geovisor
      image: geosolutionsit/mapstore2
      ports:
        - 8080:8080  

   

   geoapi:
      build: ./st-geoapi
      image: st-geoapi
      ports:
        - 5000:5000  
      environment:
        - GEOSERVER_URL=${GEOSERVER_URL}
        - GEOSERVER_GC_URL=${GEOSERVER_GC_URL}
        - GEOSERVER_USER=${GEOSERVER_USER}
        - GEOSERVER_PASSWD=${GEOSERVER_PASSWD}
        - GEOSERVER_PUBLIC_URL=${GEOSERVER_PUBLIC_URL}
        - GEOSERVER_GC_PUBLIC_URL=${GEOSERVER_GC_PUBLIC_URL}
        - MAPSTORE_URL=${MAPSTORE_URL}
        - MAPSTORE_USER=${MAPSTORE_USER}
        - MAPSTORE_PASSWD=${MAPSTORE_USER}

   nginx:
      image: nginx:latest
      ports:
        - "80:80"
        - "443:443"
      restart: on-failure
